### ISSUE TITLE
Can't launch the application

### ISSUE THREAD

**Issue by voquanghoa** [BaderEddineOuaich/spacex_stellar#1]
I have some questions:

- Can this app run on iPhone simulator (I got an error actually)?
- Can this app run on debug mode?
- We need an android release keystore file to run the app in release mode, where should we get it? (or should we create a new one?)

Thanks.

**Comment by baderouaich** [comment]
Hello there,
Sorry for the late reply.
Unfortunately this app can't run on IOS <strong>yet</strong>. 
You can run in release mode without any need of an android release keystore. simply by running command command ``flutter run --release``.
For deploying a release to the app stores, then you'll need an android release keystore. which will be a unique one created by you.

**Comment by voquanghoa** [comment]
Well done. Thank for your great job
