### ISSUE TITLE
Add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [BaderEddineOuaich/spacex_stellar#2]
Hello,

I am Maheshwari Shukla, from the team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start Flutter](https://startflutter.com/), we add open-source products that we find helpful to the community & also we provide credits to the author itself.

Let me know if you are interested to showcase your product in our open-source website.

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hearing from you.

**Comment by baderouaich** [comment]
Hello Miss Maheshwari,
I appreciate the offer, before I accept this such a great opportunity, I would like to ask some questions corresponding the offer.
First I would like to know whether the project will be published in your servers as an item to sold ?
And how/what kind of credits you provide the project authors ?
Last I would like to know if there will be anything such a contract between the author and you for documenting the offer.
I believe this is all I need to know for now. 
I’m expecting your favorable reply.
                Bader Eddine Ouaich

**Comment by maheshwari-1153** [comment]
Hello Bader, 

Thanks for getting back quickly. 

I am happy to resolve any doubts.

- It's an open-source website, so the UI will available to all without any charges.
- Credits as in, we mention the author's name along with your profile link so that other developers can reach out to you for any queries or need.
- There will no contract. Start Flutter is a platform with all the open-source UI in Flutter so that it can easily be accessible to others. 

You can check our website Start Flutter here: https://startflutter.com/

Hopefully, I have answered your queries. 

Looking forward to positive response.

**Comment by baderouaich** [comment]
Hello there,
Thank you for illuminating, i would love to get involved. a MIT License has been added to the project. if there is anything else i can help you with, i will be happy to do so. 
Best regards

**Comment by maheshwari-1153** [comment]
Thank you. I will share the link once it's uploaded.

**Comment by maheshwari-1153** [comment]
We have uploaded your UI. Please check here: https://startflutter.com/themes/spacex/
